stages:
  - build

TexCompile:
  stage: build
  tags:
    - Windows
  script:
    - $TexCompiler = "lualatex"
    - $SRC = "thesis"
    - $TexCompile = "$TexCompiler ${SRC}.tex"
    - $BibCompile = "upbibtex ${SRC}.aux"
    - Invoke-Expression $TexCompile
    - Invoke-Expression $BibCompile
    - Invoke-Expression $TexCompile
    - Invoke-Expression $TexCompile
  artifacts:
    paths:
      - ./thesis.pdf
    expire_in: 1 day
